import api from './api';
import { API_ENDPOINTS } from '../config/endpoints';

export interface DrawRequest {
  competitionId: string;
  weightClassId: string;
  drawType: 'OFFLINE_MANUAL' | 'ONLINE_AUTOMATIC';
  athleteSeeds: Array<{
    athleteId: string;
    athleteName: string;
    athleteClub: string;
    seedNumber: number;
  }>;
  notes?: string;
}

export interface DrawResponse {
  drawSessionId: string;
  competitionId: string;
  weightClassId: string;
  drawType: 'OFFLINE_MANUAL' | 'ONLINE_AUTOMATIC';
  drawnBy: string;
  drawDate: string;
  isFinal: boolean;
  notes?: string;
  results: Array<{
    athleteId: string;
    athleteName: string;
    athleteClub: string;
    seedNumber: number;
  }>;
}

export const drawService = {
  // Perform automatic draw (Online)
  async performAutomaticDraw(competitionId: string, weightClassId: string, athleteIds: string[]): Promise<DrawResponse> {
    const response = await api.post<DrawResponse>(`${API_ENDPOINTS.DRAWS.PERFORM}`, {
      competitionId,
      weightClassId,
      drawType: 'ONLINE_AUTOMATIC',
      athleteSeeds: athleteIds.map(id => ({
        athleteId: id,
        athleteName: '', // Will be filled by backend
        athleteClub: '',
        seedNumber: 0 // Will be generated by backend
      })),
      notes: 'Automatic draw performed by system'
    });
    return response.data;
  },

  // Perform manual draw (Offline)
  async performManualDraw(
    competitionId: string, 
    weightClassId: string, 
    athleteSeeds: Array<{athleteId: string, athleteName: string, athleteClub: string, seedNumber: number}>,
    notes?: string
  ): Promise<DrawResponse> {
    const response = await api.post<DrawResponse>(`${API_ENDPOINTS.DRAWS.PERFORM}`, {
      competitionId,
      weightClassId,
      drawType: 'OFFLINE_MANUAL',
      athleteSeeds,
      notes: notes || 'Manual draw performed offline'
    });
    return response.data;
  },

  // Get draw history
  async getDrawHistory(competitionId: string, weightClassId: string): Promise<DrawResponse[]> {
    const response = await api.get<DrawResponse[]>(
      `${API_ENDPOINTS.DRAWS.HISTORY.replace('{competitionId}', competitionId).replace('{weightClassId}', weightClassId)}`
    );
    return response.data;
  },

  // Get final draw
  async getFinalDraw(competitionId: string, weightClassId: string): Promise<DrawResponse | null> {
    try {
      const response = await api.get<DrawResponse>(
        `${API_ENDPOINTS.DRAWS.FINAL.replace('{competitionId}', competitionId).replace('{weightClassId}', weightClassId)}`
      );
      return response.data;
    } catch (error) {
      return null;
    }
  },

  // Finalize draw
  async finalizeDraw(drawSessionId: string): Promise<void> {
    await api.post(`${API_ENDPOINTS.DRAWS.FINALIZE.replace('{drawSessionId}', drawSessionId)}`);
  }
};
